CREATE TABLE IF NOT EXISTS `shop` ( 
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`article` CHAR(10) NOT NULL, 
`dealer` CHAR(10) NOT NULL, 
`price` FLOAT NOT NULL, 
PRIMARY KEY (`id`)) ENGINE= InnoDB DEFAULT CHARSET=utf8 
AUTO_INCREMENT=1; 